// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PhoneCallClient is the client API for PhoneCall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoneCallClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type phoneCallClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneCallClient(cc grpc.ClientConnInterface) PhoneCallClient {
	return &phoneCallClient{cc}
}

func (c *phoneCallClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/datacloak.server.PhoneCall/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneCallServer is the server API for PhoneCall service.
// All implementations must embed UnimplementedPhoneCallServer
// for forward compatibility
type PhoneCallServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedPhoneCallServer()
}

// UnimplementedPhoneCallServer must be embedded to have forward compatible implementations.
type UnimplementedPhoneCallServer struct {
}

func (UnimplementedPhoneCallServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedPhoneCallServer) mustEmbedUnimplementedPhoneCallServer() {}

// UnsafePhoneCallServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoneCallServer will
// result in compilation errors.
type UnsafePhoneCallServer interface {
	mustEmbedUnimplementedPhoneCallServer()
}

func RegisterPhoneCallServer(s grpc.ServiceRegistrar, srv PhoneCallServer) {
	s.RegisterService(&PhoneCall_ServiceDesc, srv)
}

func _PhoneCall_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneCallServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacloak.server.PhoneCall/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneCallServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhoneCall_ServiceDesc is the grpc.ServiceDesc for PhoneCall service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhoneCall_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datacloak.server.PhoneCall",
	HandlerType: (*PhoneCallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _PhoneCall_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello_world.proto",
}
