// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.5.1
// source: rpc_meta.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcMeta_Type int32

const (
	RpcMeta_REQUEST  RpcMeta_Type = 0
	RpcMeta_RESPONSE RpcMeta_Type = 1
)

// Enum value maps for RpcMeta_Type.
var (
	RpcMeta_Type_name = map[int32]string{
		0: "REQUEST",
		1: "RESPONSE",
	}
	RpcMeta_Type_value = map[string]int32{
		"REQUEST":  0,
		"RESPONSE": 1,
	}
)

func (x RpcMeta_Type) Enum() *RpcMeta_Type {
	p := new(RpcMeta_Type)
	*p = x
	return p
}

func (x RpcMeta_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcMeta_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_meta_proto_enumTypes[0].Descriptor()
}

func (RpcMeta_Type) Type() protoreflect.EnumType {
	return &file_rpc_meta_proto_enumTypes[0]
}

func (x RpcMeta_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcMeta_Type.Descriptor instead.
func (RpcMeta_Type) EnumDescriptor() ([]byte, []int) {
	return file_rpc_meta_proto_rawDescGZIP(), []int{0, 0}
}

type RpcMeta_ErrorCode int32

const (
	RpcMeta_OK             RpcMeta_ErrorCode = 0
	RpcMeta_InvalidMessage RpcMeta_ErrorCode = 1
	RpcMeta_Unknown        RpcMeta_ErrorCode = 100
)

// Enum value maps for RpcMeta_ErrorCode.
var (
	RpcMeta_ErrorCode_name = map[int32]string{
		0:   "OK",
		1:   "InvalidMessage",
		100: "Unknown",
	}
	RpcMeta_ErrorCode_value = map[string]int32{
		"OK":             0,
		"InvalidMessage": 1,
		"Unknown":        100,
	}
)

func (x RpcMeta_ErrorCode) Enum() *RpcMeta_ErrorCode {
	p := new(RpcMeta_ErrorCode)
	*p = x
	return p
}

func (x RpcMeta_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcMeta_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_meta_proto_enumTypes[1].Descriptor()
}

func (RpcMeta_ErrorCode) Type() protoreflect.EnumType {
	return &file_rpc_meta_proto_enumTypes[1]
}

func (x RpcMeta_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcMeta_ErrorCode.Descriptor instead.
func (RpcMeta_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_rpc_meta_proto_rawDescGZIP(), []int{0, 1}
}

type RpcMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       RpcMeta_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=datacloak.server.RpcMeta_Type" json:"type,omitempty"`
	Method     string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Error      RpcMeta_ErrorCode `protobuf:"varint,3,opt,name=error,proto3,enum=datacloak.server.RpcMeta_ErrorCode" json:"error,omitempty"`
	Timeout    int32             `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	SequenceId int64             `protobuf:"varint,5,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Length     int32             `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	Payload    []byte            `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RpcMeta) Reset() {
	*x = RpcMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMeta) ProtoMessage() {}

func (x *RpcMeta) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMeta.ProtoReflect.Descriptor instead.
func (*RpcMeta) Descriptor() ([]byte, []int) {
	return file_rpc_meta_proto_rawDescGZIP(), []int{0}
}

func (x *RpcMeta) GetType() RpcMeta_Type {
	if x != nil {
		return x.Type
	}
	return RpcMeta_REQUEST
}

func (x *RpcMeta) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcMeta) GetError() RpcMeta_ErrorCode {
	if x != nil {
		return x.Error
	}
	return RpcMeta_OK
}

func (x *RpcMeta) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *RpcMeta) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *RpcMeta) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *RpcMeta) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_rpc_meta_proto protoreflect.FileDescriptor

var file_rpc_meta_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6c, 0x6f, 0x61, 0x6b, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x22, 0xd6, 0x02, 0x0a, 0x07, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x32,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x63, 0x6c, 0x6f, 0x61, 0x6b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x39, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x63, 0x6c, 0x6f, 0x61, 0x6b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x70, 0x63,
	0x4d, 0x65, 0x74, 0x61, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x21, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x45, 0x10, 0x01, 0x22, 0x34, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x64, 0x42, 0x12, 0x5a, 0x10, 0x64,
	0x61, 0x74, 0x61, 0x63, 0x6c, 0x6f, 0x61, 0x6b, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_meta_proto_rawDescOnce sync.Once
	file_rpc_meta_proto_rawDescData = file_rpc_meta_proto_rawDesc
)

func file_rpc_meta_proto_rawDescGZIP() []byte {
	file_rpc_meta_proto_rawDescOnce.Do(func() {
		file_rpc_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_meta_proto_rawDescData)
	})
	return file_rpc_meta_proto_rawDescData
}

var file_rpc_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_meta_proto_goTypes = []interface{}{
	(RpcMeta_Type)(0),      // 0: datacloak.server.RpcMeta.Type
	(RpcMeta_ErrorCode)(0), // 1: datacloak.server.RpcMeta.ErrorCode
	(*RpcMeta)(nil),        // 2: datacloak.server.RpcMeta
}
var file_rpc_meta_proto_depIdxs = []int32{
	0, // 0: datacloak.server.RpcMeta.type:type_name -> datacloak.server.RpcMeta.Type
	1, // 1: datacloak.server.RpcMeta.error:type_name -> datacloak.server.RpcMeta.ErrorCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_meta_proto_init() }
func file_rpc_meta_proto_init() {
	if File_rpc_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_meta_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_meta_proto_goTypes,
		DependencyIndexes: file_rpc_meta_proto_depIdxs,
		EnumInfos:         file_rpc_meta_proto_enumTypes,
		MessageInfos:      file_rpc_meta_proto_msgTypes,
	}.Build()
	File_rpc_meta_proto = out.File
	file_rpc_meta_proto_rawDesc = nil
	file_rpc_meta_proto_goTypes = nil
	file_rpc_meta_proto_depIdxs = nil
}
